name: Build and Test Qt Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.9'  # Устанавливаем Qt 6.9
          # Опционально: укажите дополнительные модули, если они нужны вашему проекту
          # modules: 'qttools qtbase'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential

      - name: Configure project
        run: |
          cmake -S . -B build

      - name: Build project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure