name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Конфигурация CMake
        run: cmake -B build

      - name: Сборка проекта
        run: cmake --build build

      - name: Запуск тестов
        run: |
          cd build
          ctest